### ISSUE TITLE
Data Prep

### ISSUE THREAD

**Issue by mia2mia** [First-Of-His-Name/speech-emotion-recognition#1]
Hello Aman,

Quick question, how did you prepare your IEMOCAP data for loading to the model? I am trying to replicate your code but dont know how to pre-process the data.

**Comment by amanbasu** [comment]
I have used the mel frequency coefficients (MFCC) as the feature vector. The process for the same can be found in [notebook](https://github.com/First-Of-His-Name/speech-emotion-recognition/blob/master/create_mfcc.ipynb). To know more about MFCC, refer this [link](http://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html).

**Comment by mia2mia** [comment]
Thanks, I will try to replicate that and get back
