### ISSUE TITLE
Link for speech_emotion_data.pkl

### ISSUE THREAD

**Issue by thisislohith6** [First-Of-His-Name/speech-emotion-recognition#10]
Hi,
Could you please provide me the link for speech_emotion_data.pkl file that you used in speech_emotion_gpu.py python file. 
And also if possible could you upload the requirements.txt file to know the versions of the packages you used since I was facing so many errors with version changes.

Thanks in advance!

**Comment by amanbasu** [comment]
Hi @thisislohith6, please find the link to [speech_emotion_data.pkl](https://drive.google.com/file/d/10KQgGZQcOGR7Wa9UxkHe4ASDLeIm-3yU/view?usp=sharing). I cannot provide you the requirements.txt file. But FYI, this code was written for TensorFlow version less than 1.10.0.

Let me know if you have any further queries.
