### ISSUE TITLE
No Features columns in create_mfcc.ipynb

### ISSUE THREAD

**Issue by ghost** [First-Of-His-Name/speech-emotion-recognition#4]
In create_mfcc.ipynb, Features column does not exist in the 'file' dataframe. I would appreciate if you could share the code for generating features such as F0 (pitch), voice probability, zero-crossing rate and so on.

**Comment by amanbasu** [comment]
I have added [extract_features.py](https://github.com/amanbasu/speech-emotion-recognition/blob/master/extract_features.py).

**Comment by ghost** [comment]
I appreciate it.

**Comment by Jon-Zbw** [comment]
Hi Aman：
    we can do some processing of ‘features’:
 The mean value of the column is calculated directly, and we can get some one-dimensional vectors of the same length.In this way, there is no need to pad it.
This is just my personal opinion.Do you think it's feasible?
Looking forward to your reply

**Comment by amanbasu** [comment]
When predicting the emotion, in my view, it would be better if we listen to the whole sentence (signal) before making the prediction. If we trim the signals, some context/information might get lost.

But it is completely up to you. You can try both approaches and go with whichever is better.
