### ISSUE TITLE
Where is the speech_emotion_data.pkl?

### ISSUE THREAD

**Issue by Haorotu** [First-Of-His-Name/speech-emotion-recognition#6]
Hello Aman:

Thank you for enjoying your code.I am trying to follow your code.But I don't find the "speech_emotion_data.pkl" in the file of "speech_emotion_gpu.py".So please could you provide the speech_emotion_data.pkl ? Thanks very much.

Best wishes!

**Comment by amanbasu** [comment]
Thanks for your interest, the link is mentioned in the readme.
But anyway, here it is:
https://drive.google.com/file/d/1QidPJVsdUnYXj0VAGIrffmDl3pjA6RLl/view?usp=sharing

**Comment by Jon-Zbw** [comment]
Hello Aman:
Thks for your reply. I got some problems again :  'speech_emotion_data.pkl ' in speech_emotion_gpu.py 、‘mfcc_feat.pkl’ in create_mfcc.ipynb 、'feature' in extract_features.py .   These three files are the same？？？

**Comment by Jon-Zbw** [comment]
Add: I can't open this ：https://drive.google.com/file/d/1QidPJVsdUnYXj0VAGIrffmDl3pjA6RLl/view?usp=sharing.

**Comment by amanbasu** [comment]
`mfcc_feat.pkl` in create_mfcc.ipynb: only contains MFCC features and corresponding emotion labels.
`feature` in extract_features.py: contains only feature values (more than MFCC).
`speech_emotion_data.pkl` in speech_emotion_gpu.py: contains `feature` values along with labels.
Apologies for the terminology of files.

Here is the link for `speech_emotion_data.pkl` file:
https://drive.google.com/file/d/10KQgGZQcOGR7Wa9UxkHe4ASDLeIm-3yU/view?usp=sharing

Let me know if somehow this link gets invalidated again.

**Comment by Jon-Zbw** [comment]
Tks very much ，I got it.   Actually, I'm using my own data set. however，my generated mfcc_feat.pkl file is garbled code.But those features can be printed in Pycharm

**Comment by zbw66** [comment]
Question1   in this line: feed_dict={"MFCC":final_vector.astype(np.float64),"name":file.split('/')[-1].split('.')[0]}
                     print(feed_dict)
                     output:{'MFCC': array([-5.04838684e+00,  9.23772341e+00,  9.10832953e+00,  1.09154333e+01,..............
                                 ,9.97365337e+00, -8.78606747e+00]), 'name': ''}
          'name': ''   why nothing in  ' ' ???  
Question2   in this line: with gzip.open('mfcc_feat.pkl', 'rb') as ifp:
                                     file = pickle.load(ifp)
                         output:       Traceback (most recent call last):
                                            File "D:/Project/pycharm/RNN/create_mfcc.py", line 59, in <module>
                                                      file = pickle.load(ifp)
                                            File "D:\Miniconda3\lib\gzip.py", line 296, in peek
                                                      return self._buffer.peek(n)
                                            File "D:\Miniconda3\lib\_compression.py", line 68, in readinto
                                                      data = self.read(len(byte_view))
                                            File "D:\Miniconda3\lib\gzip.py", line 463, in read
                                                      if not self._read_gzip_header():
                                            File "D:\Miniconda3\lib\gzip.py", line 411, in _read_gzip_header
                                                      raise OSError('Not a gzipped file (%r)' % magic)
                                            OSError: Not a gzipped file (b'\x80\x04')

**Comment by zbw66** [comment]
Question1   was  figured  out
question 2  still  there

**Comment by Jon-Zbw** [comment]
Hi  Aman . im coming again  HAHA
from tensorflow.contrib import rnn
from tensorflow.contrib.rnn import stack_bidirectional_dynamic_rnn
ModuleNotFoundError: No module named 'tensorflow.contrib'
my version of tensoflow is 2.2.0  and because of other project ，i  dont  wanna reduce this version 
how to deal with it？

**Comment by amanbasu** [comment]
Hi @zbw66, we used the 1.10.0 version probably. So, to run the same code on 2.2.0, you need to find the replacement of `stack_bidirectional_dynamic_rnn` in some other module.

**Comment by Jon-Zbw** [comment]
ok  Thanks for your patience. I'll try to create an environment like yours
Reconfirm：I would like to know the ’’python‘‘ and ‘’tensorflow‘’ version of this project

**Comment by amanbasu** [comment]
Python 3.6, TensorFlow 1.10.0.

**Comment by zbw66** [comment]
Hi Aman:
I have some problems here.:

firstly：
      df = df.reset_index()
      print(df)
[output]:          index   ...       name
                   0       0      ...           a
                   1       1      ...           b
                   2       2      ...           c
                ...bla    bla    ...          bla
      
               [64 rows * 3 columns]
secondly:
       F=df. drop('index' , inplace=True , axis=1)   
       print(F)    
[output]:  None  (i dont know why????)

thirdly:
for index, row in df.iterrows():
    df.set_value(index, 'lengths', row['Features'].shape[0])

‘’set_value‘’ became to ‘’at‘’

so：    df.at(index, 'lengths', row['Features'].shape[0])
but:     Traceback (most recent call last):
            File "D:/Project/pycharm/RNN/create_mfcc.py", line 86, in <module>
                   df.at(index, 'lengths', row['MFCC'].shape[0])
                   TypeError: '_AtIndexer' object is not callable

**Comment by zbw66** [comment]
Hi Aman:
I have some problems here.:

firstly：
df = df.reset_index()
print(df)
[output]: 
   index ... name
0     0    ...   a
1     1    ...   b
2     2    ...   c
...bla bla ... bla
 [64 rows * 3 columns]
secondly:
F=df. drop('index' , inplace=True , axis=1)
print(F)
[output]: 
None (i dont know why????)

thirdly:
for index, row in df.iterrows():
df.set_value(index, 'lengths', row['Features'].shape[0])

‘’set_value‘’ became to ‘’at‘’

so： df.at(index, 'lengths', row['Features'].shape[0])
but: Traceback (most recent call last):
File "D:/Project/pycharm/RNN/create_mfcc.py", line 86, in 
            df.at(index, 'lengths', row['MFCC'].shape[0])
            TypeError: '_AtIndexer' object is not callable

**Comment by Jon-Zbw** [comment]
Hi Aman:
I have some problems here.:

firstly：
df = df.reset_index()
print(df)
[output]:
index ... name
0 0 ... a
1 1 ... b
2 2 ... c
...bla bla ... bla          （I don't know. Can you read this typesetting?   HAHA）
[64 rows * 3 columns]

secondly:
F=df. drop('index' , inplace=True , axis=1)
print(F)
[output]:
None (i dont know why????)

thirdly:
for index, row in df.iterrows():
df.set_value(index, 'lengths', row['Features'].shape[0])

‘’set_value‘’ became to ‘’at‘’

so：
 df.at(index, 'lengths', row['Features'].shape[0])
but: 
Traceback (most recent call last):
File "D:/Project/pycharm/RNN/create_mfcc.py", line 86, in
df.at(index, 'lengths', row['MFCC'].shape[0])
TypeError: '_AtIndexer' object is not callable
