### ISSUE TITLE
misssing files  Ses01F_script01_2_F008.wav and microsoft_32_features.pkl

### ISSUE THREAD

**Issue by Avi143** [First-Of-His-Name/speech-emotion-recognition#7]
Dear sir,

I appropriate your work, i'm student at GMR Institute of Technology,Rajam. As a part of the Project, i am working (Speech to emotion recognition using RNN). For reference i have seen your github. (https://github.com/amanbasu/speech-emotion-recognition.git).

But there are some files are missing in the repository.

Could you please share those data with me?

Ses01F_script01_2_F008.wav
microsoft_32_features.pkl

i couldn't understand the

"path_to_database/IEMOCAP_database/Session{}/wav/*/*.wav".

because of this i couldn't able to load the data...Please help me in this regard

Please respond to the mail as early as possible

Thank you.

**Comment by amanbasu** [comment]
1. "Could you please share those data with me? Ses01F_script01_2_F008.wav"

The files are available in the IEMOCAP dataset (check this [link](https://sail.usc.edu/iemocap/iemocap_release.htm) for more information).

2. "microsoft_32_features.pkl"

The [link](https://drive.google.com/file/d/1QidPJVsdUnYXj0VAGIrffmDl3pjA6RLl/view) is mentioned in the readme. Moreover, use [this](https://github.com/amanbasu/speech-emotion-recognition/blob/master/extract_features.py) code to build it yourself.

3. "i couldn't understand the path_to_database/IEMOCAP_database/Session{}/wav//.wav"

This line reads all the .wav files in the dataset. You will know once you download the data.

**Comment by Avi143** [comment]
Thank you so much sir for your quick response.
